#!/bin/sh
FAIL=0
#zero systJetE+ systJetE- systPhE+ systPhE- systElE+ systElE- systAcc  
for i in zero systJetE+ systJetE- systPhE+ systPhE- systElE+ systElE- systAcc  
do
	#q2_lt_30 q2_gt_30 
	for j in ""
	do 
	    ./start_photonssys $i $j &
	    echo "starting ($i)"  
	    wait || echo "an error occured"
	done
done

for job in `jobs -p`
do
    echo $job
    wait $job || let "FAIL+=1"
done
echo $FAIL
if [ "$FAIL" == "0" ];
then
echo "startfor YAY!"
else
echo "startfor FAIL! ($FAIL) ($i)"
fi
echo "startfor end ($i)"
echo "your computation is done COMP" | mail -s "png ready" "greyxray@gmail.com"
