#!/bin/sh


for i in systElE+ systElE- 
do
    FAIL=0
    echo "starting ($i)"
    ./main 0405e data 0 0 0 $i > /dev/null 2> /dev/null &
    ./main 06e data 0 0 0 $i > /dev/null 2> /dev/null &
    ./main 0607p data 0 0 0 $i > /dev/null 2> /dev/null &
       
    ./main 0405e mc_bg_rad 0 0 0 $i > /dev/null 2> /dev/null &
    ./main 06e mc_bg_rad 0 0 0 $i > /dev/null 2> /dev/null &
    ./main 0607p mc_bg_rad 0 0 0 $i > /dev/null 2> /dev/null &
      
    ./main 0405e mc_bg_norad 0 0 0 $i > /dev/null 2> /dev/null &
    ./main 06e mc_bg_norad 0 0 0 $i > /dev/null 2> /dev/null &
    ./main 0607p mc_bg_norad 0 0 0 $i > /dev/null 2> /dev/null &
      
    ./main 0405e mc_prph 0 0 0 $i > /dev/null 2> /dev/null &
    ./main 06e mc_prph 0 0 0 $i > /dev/null 2> /dev/null &
    
    wait
    echo "end ($i)"
done
