#!/bin/sh
i = zero

if [ "$1" ]
then
 i="$1"
fi

FAIL=0

#systJetE+ systJetE- systPhE+ systPhE- systElE+ systElE- systAcc

echo "starting ($i)"
if [ "$i" == "zero" ]
then
 ./main 0405e data 0 0 0 $i > /dev/null 2> /dev/null &
 ./main 06e data 0 0 0 $i > /dev/null 2> /dev/null &
 ./main 0607p data 0 0 0 $i > /dev/null 2> /dev/null &
fi
       
./main 0405e mc_bg_rad 0 0 0 $i > /dev/null 2> /dev/null &
./main 06e mc_bg_rad 0 0 0 $i > /dev/null 2> /dev/null &
./main 0607p mc_bg_rad 0 0 0 $i > /dev/null 2> /dev/null &
    
./main 0405e mc_bg_norad 0 0 0 $i > /dev/null 2> /dev/null &
./main 06e mc_bg_norad 0 0 0 $i > /dev/null 2> /dev/null &
./main 0607p mc_bg_norad 0 0 0 $i > /dev/null 2> /dev/null &
    
./main 0405e mc_prph 0 0 0 $i > /dev/null 2> /dev/null &
./main 06e mc_prph 0 0 0 $i > /dev/null 2> /dev/null &


for job in `jobs -p`
do
    echo $job
    wait $job || let "FAIL+=1"
done
echo $FAIL
if [ "$FAIL" == "0" ];
then
echo "YAY!"
else
echo "FAIL! ($FAIL)"
fi
echo "end ($i)"