#!/bin/sh

cp /afs/desy.de/user/g/glusheno/zeus/dustexchange/hist_calculate_cross_sec.c /nfs/dust/zeus/group/glushenko/isolated_photons_summer/cross_sec_EB/hist_calculate_cross_sec.c
touch output.txt
./p cross_sec >> output.txt
cp  /nfs/dust/zeus/group/glushenko/isolated_photons_summer/cross_sec_EB/output.txt /afs/desy.de/user/g/glusheno/zeus/dustexchange/output.txt 
rm output.txt
