{
//=========Macro generated from canvas: canv_cross_et/
//=========  (Mon Sep 14 17:32:40 2015) by ROOT version5.34/00
   TCanvas *canv_cross_et = new TCanvas("canv_cross_et", "",1,1,1200,976);
   canv_cross_et->SetHighLightColor(2);
   canv_cross_et->Range(0,0,1,1);
   canv_cross_et->SetFillColor(0);
   canv_cross_et->SetBorderMode(0);
   canv_cross_et->SetBorderSize(2);
   canv_cross_et->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: canv_cross_et_1
   TPad *canv_cross_et_1 = new TPad("canv_cross_et_1", "canv_cross_et_1",0.01,0.01,0.99,0.99);
   canv_cross_et_1->Draw();
   canv_cross_et_1->cd();
   canv_cross_et_1->Range(1.9375,-0.8616438,15.6875,4.480822);
   canv_cross_et_1->SetFillColor(0);
   canv_cross_et_1->SetBorderMode(0);
   canv_cross_et_1->SetBorderSize(2);
   canv_cross_et_1->SetTickx(1);
   canv_cross_et_1->SetTicky(1);
   canv_cross_et_1->SetLeftMargin(0.15);
   canv_cross_et_1->SetRightMargin(0.05);
   canv_cross_et_1->SetBottomMargin(0.18);
   canv_cross_et_1->SetFrameBorderMode(0);
   canv_cross_et_1->SetFrameBorderMode(0);
   Double_t xAxis37[5] = {4, 6, 8, 10, 15}; 
   
   TH2D *h_window_cross_et = new TH2D("h_window_cross_et","",4, xAxis37,10,0.1,4);
   h_window_cross_et->SetStats(0);
   h_window_cross_et->GetXaxis()->SetTitle("E_{T}^{#gamma} (GeV)");
   h_window_cross_et->GetXaxis()->SetNdivisions(507);
   h_window_cross_et->GetXaxis()->SetLabelFont(22);
   h_window_cross_et->GetXaxis()->SetLabelSize(0.05424658);
   h_window_cross_et->GetXaxis()->SetTitleSize(0.06027398);
   h_window_cross_et->GetXaxis()->SetTitleOffset(1.02);
   h_window_cross_et->GetXaxis()->SetTitleFont(22);
   h_window_cross_et->GetYaxis()->SetTitle("d#sigma/dE_{T}^{#gamma} (pb/GeV)");
   h_window_cross_et->GetYaxis()->SetNdivisions(507);
   h_window_cross_et->GetYaxis()->SetLabelFont(22);
   h_window_cross_et->GetYaxis()->SetLabelOffset(0.016);
   h_window_cross_et->GetYaxis()->SetLabelSize(0.05424658);
   h_window_cross_et->GetYaxis()->SetTitleSize(0.06027398);
   h_window_cross_et->GetYaxis()->SetTitleOffset(0.94);
   h_window_cross_et->GetYaxis()->SetTitleFont(22);
   h_window_cross_et->Draw("");
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(4);
   grae->SetName("Graph");
   grae->SetTitle("Graph");
   grae->SetFillColor(42);
   grae->SetPoint(0,5,2.490761);
   grae->SetPointError(0,0,0,0.2968731,0.2785703);
   grae->SetPoint(1,7,1.347578);
   grae->SetPointError(1,0,0,0.1392948,0.07028056);
   grae->SetPoint(2,9,0.6555723);
   grae->SetPointError(2,0,0,0.04801636,0.03792059);
   grae->SetPoint(3,12.5,0.2518526);
   grae->SetPointError(3,0,0,0.01395105,0.01565746);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","Graph",100,4.25,13.25);
   Graph_Graph1->SetMinimum(0);
   Graph_Graph1->SetMaximum(3.022474);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_Graph1);
   
   grae->Draw("e3 ");
   Double_t xAxis38[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et = new TH1D("h_cross_section_et","det_cross_et",4, xAxis38);
   h_cross_section_et->SetBinContent(1,2.380595);
   h_cross_section_et->SetBinContent(2,1.281126);
   h_cross_section_et->SetBinContent(3,0.615687);
   h_cross_section_et->SetBinContent(4,0.2556284);
   h_cross_section_et->SetBinError(1,0.1767385);
   h_cross_section_et->SetBinError(2,0.1017351);
   h_cross_section_et->SetBinError(3,0.07578678);
   h_cross_section_et->SetBinError(4,0.02508957);
   h_cross_section_et->SetEntries(14099);
   h_cross_section_et->SetFillColor(41);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   h_cross_section_et->SetLineColor(ci);
   h_cross_section_et->SetLineWidth(2);
   h_cross_section_et->SetMarkerStyle(20);
   h_cross_section_et->GetXaxis()->SetLabelFont(42);
   h_cross_section_et->GetXaxis()->SetLabelSize(0.035);
   h_cross_section_et->GetXaxis()->SetTitleSize(0.035);
   h_cross_section_et->GetXaxis()->SetTitleFont(42);
   h_cross_section_et->GetYaxis()->SetLabelFont(42);
   h_cross_section_et->GetYaxis()->SetLabelSize(0.035);
   h_cross_section_et->GetYaxis()->SetTitleSize(0.035);
   h_cross_section_et->GetYaxis()->SetTitleFont(42);
   h_cross_section_et->GetZaxis()->SetLabelFont(42);
   h_cross_section_et->GetZaxis()->SetLabelSize(0.035);
   h_cross_section_et->GetZaxis()->SetTitleSize(0.035);
   h_cross_section_et->GetZaxis()->SetTitleFont(42);
   h_cross_section_et->Draw("E1 X0 SAME");
   
   grae = new TGraphAsymmErrors(4);
   grae->SetName("Graph");
   grae->SetTitle("Graph");
   grae->SetFillColor(1);
   grae->SetMarkerStyle(20);
   grae->SetPoint(0,5,2.490761);
   grae->SetPointError(0,0,0,0.3544237,0.2737973);
   grae->SetPoint(1,7,1.347578);
   grae->SetPointError(1,0,0,0.1764266,0.1531228);
   grae->SetPoint(2,9,0.6555723);
   grae->SetPointError(2,0,0,0.09059639,0.1086475);
   grae->SetPoint(3,12.5,0.2518526);
   grae->SetPointError(3,0,0,0.03162241,0.0401334);
   grae->Draw("e ");
   
   TLegend *leg = new TLegend(0.3,0.65,0.9,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_cross_section_et","ZEUS (332 pb^{-1})","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","systematic uncertainty","f");
   entry->SetFillColor(42);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","inner error bars are stat. uncertainties","le");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","outer error bars are total uncertainties","le");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   leg = new TLegend(0.5,0.25,0.9,0.65,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("NULL","At the bottom:","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("Graph","jet energy uncertainty","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3454);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","photon energy uncertainty","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3445);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","electron energy uncertainty","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3425);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","#delta Z range unc.","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3452);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Graph","total syst. unc.","le");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   canv_cross_et_1->Modified();
   canv_cross_et->cd();
   TText *text = new TText(0.45,0.95,"ZEUS");
   text->SetTextFont(22);
   text->SetTextSize(0.07);
   text->Draw();
   canv_cross_et->Modified();
   canv_cross_et->cd();
   canv_cross_et->SetSelected(canv_cross_et);
}
