{
//=========Macro generated from canvas: canv_cross_eta_jet/
//=========  (Fri Mar 11 01:30:26 2011) by ROOT version5.26/00c
   TCanvas *canv_cross_eta_jet = new TCanvas("canv_cross_eta_jet", "",0,0,550,900);
   canv_cross_eta_jet->SetHighLightColor(2);
   canv_cross_eta_jet->Range(0,0,1,1);
   canv_cross_eta_jet->SetFillColor(0);
   canv_cross_eta_jet->SetBorderMode(0);
   canv_cross_eta_jet->SetBorderSize(2);
   canv_cross_eta_jet->SetTopMargin(0.04761905);
   canv_cross_eta_jet->SetBottomMargin(0.05);
   canv_cross_eta_jet->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: canv_cross_eta_jet_1
   TPad *canv_cross_eta_jet_1 = new TPad("canv_cross_eta_jet_1", "_1",0.1,0.4,0.9,0.9);
   canv_cross_eta_jet_1->Draw();
   canv_cross_eta_jet_1->cd();
   canv_cross_eta_jet_1->Range(-2.023171,0.05,2.00122,4);
   canv_cross_eta_jet_1->SetFillColor(0);
   canv_cross_eta_jet_1->SetBorderMode(0);
   canv_cross_eta_jet_1->SetBorderSize(2);
   canv_cross_eta_jet_1->SetTickx(1);
   canv_cross_eta_jet_1->SetTicky(1);
   canv_cross_eta_jet_1->SetLeftMargin(0.13);
   canv_cross_eta_jet_1->SetRightMargin(0.05);
   canv_cross_eta_jet_1->SetTopMargin(0);
   canv_cross_eta_jet_1->SetBottomMargin(0);
   canv_cross_eta_jet_1->SetFrameBorderMode(0);
   canv_cross_eta_jet_1->SetFrameBorderMode(0);
   Double_t xAxis61[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH2D *h_window_cross_eta_jet = new TH2D("h_window_cross_eta_jet","",4, xAxis61,10,0.05,4);
   h_window_cross_eta_jet->SetStats(0);
   h_window_cross_eta_jet->GetXaxis()->SetTitle("#eta_{jet}");
   h_window_cross_eta_jet->GetXaxis()->CenterTitle(true);
   h_window_cross_eta_jet->GetXaxis()->SetNdivisions(507);
   h_window_cross_eta_jet->GetXaxis()->SetLabelFont(42);
   h_window_cross_eta_jet->GetXaxis()->SetLabelSize(0.05073171);
   h_window_cross_eta_jet->GetXaxis()->SetTitleSize(0.06341463);
   h_window_cross_eta_jet->GetXaxis()->SetTitleFont(42);
   h_window_cross_eta_jet->GetYaxis()->SetTitle("d#sigma/d #eta_{jet} (pb)");
   h_window_cross_eta_jet->GetYaxis()->CenterTitle(true);
   h_window_cross_eta_jet->GetYaxis()->SetNdivisions(507);
   h_window_cross_eta_jet->GetYaxis()->SetLabelFont(42);
   h_window_cross_eta_jet->GetYaxis()->SetLabelSize(0.0416);
   h_window_cross_eta_jet->GetYaxis()->SetTitleSize(0.052);
   h_window_cross_eta_jet->GetYaxis()->SetTitleFont(42);
   h_window_cross_eta_jet->Draw("");
   Double_t xAxis62[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet = new TH1D("h_cross_section_eta_jet","det_cross_eta_jet",4, xAxis62);
   h_cross_section_eta_jet->SetBinContent(0,23859.31);
   h_cross_section_eta_jet->SetBinContent(1,nan);
   h_cross_section_eta_jet->SetBinContent(2,nan);
   h_cross_section_eta_jet->SetBinContent(3,nan);
   h_cross_section_eta_jet->SetBinContent(4,nan);
   h_cross_section_eta_jet->SetBinError(0,154.4646);
   h_cross_section_eta_jet->SetBinError(1,nan);
   h_cross_section_eta_jet->SetBinError(2,nan);
   h_cross_section_eta_jet->SetBinError(3,nan);
   h_cross_section_eta_jet->SetBinError(4,nan);
   h_cross_section_eta_jet->SetEntries(22622);
   h_cross_section_eta_jet->SetFillColor(41);
   h_cross_section_eta_jet->SetMarkerStyle(20);
   h_cross_section_eta_jet->SetMarkerSize(0.8);
   h_cross_section_eta_jet->Draw("E3 SAME");
   Double_t xAxis63[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet_stat_fit_err = new TH1D("h_cross_section_eta_jet_stat_fit_err","det_cross_eta_jet",4, xAxis63);
   h_cross_section_eta_jet_stat_fit_err->SetBinContent(0,23859.31);
   h_cross_section_eta_jet_stat_fit_err->SetBinContent(1,nan);
   h_cross_section_eta_jet_stat_fit_err->SetBinContent(2,nan);
   h_cross_section_eta_jet_stat_fit_err->SetBinContent(3,nan);
   h_cross_section_eta_jet_stat_fit_err->SetBinContent(4,nan);
   h_cross_section_eta_jet_stat_fit_err->SetBinError(0,154.4646);
   h_cross_section_eta_jet_stat_fit_err->SetBinError(1,nan);
   h_cross_section_eta_jet_stat_fit_err->SetBinError(2,nan);
   h_cross_section_eta_jet_stat_fit_err->SetBinError(3,nan);
   h_cross_section_eta_jet_stat_fit_err->SetBinError(4,nan);
   h_cross_section_eta_jet_stat_fit_err->SetEntries(22622);
   h_cross_section_eta_jet_stat_fit_err->SetFillColor(43);
   h_cross_section_eta_jet_stat_fit_err->Draw("E3 SAME");
   Double_t xAxis64[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet_acc_err = new TH1D("h_cross_section_eta_jet_acc_err","det_cross_eta_jet",4, xAxis64);
   h_cross_section_eta_jet_acc_err->SetBinContent(0,23859.31);
   h_cross_section_eta_jet_acc_err->SetBinContent(1,nan);
   h_cross_section_eta_jet_acc_err->SetBinContent(2,nan);
   h_cross_section_eta_jet_acc_err->SetBinContent(3,nan);
   h_cross_section_eta_jet_acc_err->SetBinContent(4,nan);
   h_cross_section_eta_jet_acc_err->SetBinError(0,154.4646);
   h_cross_section_eta_jet_acc_err->SetBinError(1,nan);
   h_cross_section_eta_jet_acc_err->SetBinError(2,nan);
   h_cross_section_eta_jet_acc_err->SetBinError(3,nan);
   h_cross_section_eta_jet_acc_err->SetBinError(4,nan);
   h_cross_section_eta_jet_acc_err->SetEntries(22622);
   h_cross_section_eta_jet_acc_err->SetFillColor(46);
   h_cross_section_eta_jet_acc_err->Draw("E3 SAME");
   Double_t xAxis65[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet_lumi_err = new TH1D("h_cross_section_eta_jet_lumi_err","det_cross_eta_jet",4, xAxis65);
   h_cross_section_eta_jet_lumi_err->SetBinContent(0,23859.31);
   h_cross_section_eta_jet_lumi_err->SetBinContent(1,nan);
   h_cross_section_eta_jet_lumi_err->SetBinContent(2,nan);
   h_cross_section_eta_jet_lumi_err->SetBinContent(3,nan);
   h_cross_section_eta_jet_lumi_err->SetBinContent(4,nan);
   h_cross_section_eta_jet_lumi_err->SetBinError(0,154.4646);
   h_cross_section_eta_jet_lumi_err->SetBinError(1,nan);
   h_cross_section_eta_jet_lumi_err->SetBinError(2,nan);
   h_cross_section_eta_jet_lumi_err->SetBinError(3,nan);
   h_cross_section_eta_jet_lumi_err->SetBinError(4,nan);
   h_cross_section_eta_jet_lumi_err->SetEntries(22622);
   h_cross_section_eta_jet_lumi_err->SetFillColor(49);
   h_cross_section_eta_jet_lumi_err->Draw("E3 SAME");
   Double_t xAxis66[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet = new TH1D("h_cross_section_eta_jet","det_cross_eta_jet",4, xAxis66);
   h_cross_section_eta_jet->SetBinContent(0,23859.31);
   h_cross_section_eta_jet->SetBinContent(1,nan);
   h_cross_section_eta_jet->SetBinContent(2,nan);
   h_cross_section_eta_jet->SetBinContent(3,nan);
   h_cross_section_eta_jet->SetBinContent(4,nan);
   h_cross_section_eta_jet->SetBinError(0,154.4646);
   h_cross_section_eta_jet->SetBinError(1,nan);
   h_cross_section_eta_jet->SetBinError(2,nan);
   h_cross_section_eta_jet->SetBinError(3,nan);
   h_cross_section_eta_jet->SetBinError(4,nan);
   h_cross_section_eta_jet->SetEntries(22622);
   h_cross_section_eta_jet->SetFillColor(41);
   h_cross_section_eta_jet->SetMarkerStyle(20);
   h_cross_section_eta_jet->SetMarkerSize(0.8);
   h_cross_section_eta_jet->Draw("E1 X0 SAME");
   
   TLegend *leg = new TLegend(0.37,0.059,0.77,0.458,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_cross_section_eta_jet","ZEUS (332 pb^{-1})","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry=leg->AddEntry("h_cross_section_eta_jet_stat_fit_err","statistic & fit parameter unc.","f");
   entry->SetFillColor(43);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_eta_jet_acc_err","acceptance unc.","f");
   entry->SetFillColor(46);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_eta_jet_lumi_err","luminosity unc.","f");
   entry->SetFillColor(49);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_eta_jet","total unc.","fpl");
   entry->SetFillColor(41);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   leg->Draw();
   canv_cross_eta_jet_1->Modified();
   canv_cross_eta_jet->cd();
  
// ------------>Primitives in pad: canv_cross_eta_jet_2
   canv_cross_eta_jet_2 = new TPad("canv_cross_eta_jet_2", "_2",0.1,0.2,0.9,0.4);
   canv_cross_eta_jet_2->Draw();
   canv_cross_eta_jet_2->cd();
   canv_cross_eta_jet_2->Range(-2.023171,-0.7083333,2.00122,0.425);
   canv_cross_eta_jet_2->SetFillColor(0);
   canv_cross_eta_jet_2->SetBorderMode(0);
   canv_cross_eta_jet_2->SetBorderSize(2);
   canv_cross_eta_jet_2->SetTickx(1);
   canv_cross_eta_jet_2->SetTicky(1);
   canv_cross_eta_jet_2->SetLeftMargin(0.13);
   canv_cross_eta_jet_2->SetRightMargin(0.05);
   canv_cross_eta_jet_2->SetTopMargin(0);
   canv_cross_eta_jet_2->SetBottomMargin(0.25);
   canv_cross_eta_jet_2->SetFrameBorderMode(0);
   canv_cross_eta_jet_2->SetFrameBorderMode(0);
   Double_t xAxis67[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH2D *h_window_cross_ratio_eta_jet = new TH2D("h_window_cross_ratio_eta_jet","",4, xAxis67,10,-0.425,0.425);
   h_window_cross_ratio_eta_jet->SetStats(0);
   h_window_cross_ratio_eta_jet->GetXaxis()->SetTitle("#eta_{jet}");
   h_window_cross_ratio_eta_jet->GetXaxis()->CenterTitle(true);
   h_window_cross_ratio_eta_jet->GetXaxis()->SetNdivisions(507);
   h_window_cross_ratio_eta_jet->GetXaxis()->SetLabelFont(42);
   h_window_cross_ratio_eta_jet->GetXaxis()->SetLabelSize(0.09756097);
   h_window_cross_ratio_eta_jet->GetXaxis()->SetTitleSize(0.1219512);
   h_window_cross_ratio_eta_jet->GetXaxis()->SetTickLength(0.07);
   h_window_cross_ratio_eta_jet->GetXaxis()->SetTitleOffset(0.8);
   h_window_cross_ratio_eta_jet->GetXaxis()->SetTitleFont(42);
   h_window_cross_ratio_eta_jet->GetYaxis()->SetTitle("rel. uncertainty");
   h_window_cross_ratio_eta_jet->GetYaxis()->CenterTitle(true);
   h_window_cross_ratio_eta_jet->GetYaxis()->SetNdivisions(406);
   h_window_cross_ratio_eta_jet->GetYaxis()->SetLabelFont(42);
   h_window_cross_ratio_eta_jet->GetYaxis()->SetLabelSize(0.08533333);
   h_window_cross_ratio_eta_jet->GetYaxis()->SetTitleSize(0.1066667);
   h_window_cross_ratio_eta_jet->GetYaxis()->SetTitleOffset(0.5);
   h_window_cross_ratio_eta_jet->GetYaxis()->SetTitleFont(42);
   h_window_cross_ratio_eta_jet->Draw("");
   Double_t xAxis68[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet_ratio = new TH1D("h_cross_section_eta_jet_ratio","det_cross_eta_jet",4, xAxis68);
   h_cross_section_eta_jet_ratio->SetBinContent(0,23859.31);
   h_cross_section_eta_jet_ratio->SetBinError(0,154.4646);
   h_cross_section_eta_jet_ratio->SetBinError(1,nan);
   h_cross_section_eta_jet_ratio->SetBinError(2,nan);
   h_cross_section_eta_jet_ratio->SetBinError(3,nan);
   h_cross_section_eta_jet_ratio->SetBinError(4,nan);
   h_cross_section_eta_jet_ratio->SetEntries(22622);
   h_cross_section_eta_jet_ratio->SetFillColor(41);
   h_cross_section_eta_jet_ratio->SetMarkerStyle(20);
   h_cross_section_eta_jet_ratio->SetMarkerSize(0.8);
   h_cross_section_eta_jet_ratio->Draw("E3 SAME");
   Double_t xAxis69[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet_stat_fit_err_ratio = new TH1D("h_cross_section_eta_jet_stat_fit_err_ratio","det_cross_eta_jet",4, xAxis69);
   h_cross_section_eta_jet_stat_fit_err_ratio->SetBinContent(0,23859.31);
   h_cross_section_eta_jet_stat_fit_err_ratio->SetBinError(0,154.4646);
   h_cross_section_eta_jet_stat_fit_err_ratio->SetBinError(1,nan);
   h_cross_section_eta_jet_stat_fit_err_ratio->SetBinError(2,nan);
   h_cross_section_eta_jet_stat_fit_err_ratio->SetBinError(3,nan);
   h_cross_section_eta_jet_stat_fit_err_ratio->SetBinError(4,nan);
   h_cross_section_eta_jet_stat_fit_err_ratio->SetEntries(22622);
   h_cross_section_eta_jet_stat_fit_err_ratio->SetFillColor(43);
   h_cross_section_eta_jet_stat_fit_err_ratio->Draw("E3 SAME");
   Double_t xAxis70[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet_acc_err_ratio = new TH1D("h_cross_section_eta_jet_acc_err_ratio","det_cross_eta_jet",4, xAxis70);
   h_cross_section_eta_jet_acc_err_ratio->SetBinContent(0,23859.31);
   h_cross_section_eta_jet_acc_err_ratio->SetBinError(0,154.4646);
   h_cross_section_eta_jet_acc_err_ratio->SetBinError(1,nan);
   h_cross_section_eta_jet_acc_err_ratio->SetBinError(2,nan);
   h_cross_section_eta_jet_acc_err_ratio->SetBinError(3,nan);
   h_cross_section_eta_jet_acc_err_ratio->SetBinError(4,nan);
   h_cross_section_eta_jet_acc_err_ratio->SetEntries(22622);
   h_cross_section_eta_jet_acc_err_ratio->SetFillColor(46);
   h_cross_section_eta_jet_acc_err_ratio->Draw("E3 SAME");
   Double_t xAxis71[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet_lumi_err_ratio = new TH1D("h_cross_section_eta_jet_lumi_err_ratio","det_cross_eta_jet",4, xAxis71);
   h_cross_section_eta_jet_lumi_err_ratio->SetBinContent(0,23859.31);
   h_cross_section_eta_jet_lumi_err_ratio->SetBinError(0,154.4646);
   h_cross_section_eta_jet_lumi_err_ratio->SetBinError(1,nan);
   h_cross_section_eta_jet_lumi_err_ratio->SetBinError(2,nan);
   h_cross_section_eta_jet_lumi_err_ratio->SetBinError(3,nan);
   h_cross_section_eta_jet_lumi_err_ratio->SetBinError(4,nan);
   h_cross_section_eta_jet_lumi_err_ratio->SetEntries(22622);
   h_cross_section_eta_jet_lumi_err_ratio->SetFillColor(49);
   h_cross_section_eta_jet_lumi_err_ratio->Draw("E3 SAME");
   Double_t xAxis72[5] = {-1.5, -0.7, 0.1, 0.9, 1.8}; 
   
   TH1D *h_cross_section_eta_jet_ratio = new TH1D("h_cross_section_eta_jet_ratio","det_cross_eta_jet",4, xAxis72);
   h_cross_section_eta_jet_ratio->SetBinContent(0,23859.31);
   h_cross_section_eta_jet_ratio->SetBinError(0,154.4646);
   h_cross_section_eta_jet_ratio->SetBinError(1,nan);
   h_cross_section_eta_jet_ratio->SetBinError(2,nan);
   h_cross_section_eta_jet_ratio->SetBinError(3,nan);
   h_cross_section_eta_jet_ratio->SetBinError(4,nan);
   h_cross_section_eta_jet_ratio->SetEntries(22622);
   h_cross_section_eta_jet_ratio->SetFillColor(41);
   h_cross_section_eta_jet_ratio->SetMarkerStyle(20);
   h_cross_section_eta_jet_ratio->SetMarkerSize(0.8);
   h_cross_section_eta_jet_ratio->Draw("E1 X0 SAME");
   canv_cross_eta_jet_2->Modified();
   canv_cross_eta_jet->cd();
   canv_cross_eta_jet->Modified();
   canv_cross_eta_jet->cd();
   canv_cross_eta_jet->SetSelected(canv_cross_eta_jet);
}
