{
//=========Macro generated from canvas: canv_cross_et/
//=========  (Fri Mar 11 01:30:26 2011) by ROOT version5.26/00c
   TCanvas *canv_cross_et = new TCanvas("canv_cross_et", "",0,0,550,900);
   canv_cross_et->SetHighLightColor(2);
   canv_cross_et->Range(0,0,1,1);
   canv_cross_et->SetFillColor(0);
   canv_cross_et->SetBorderMode(0);
   canv_cross_et->SetBorderSize(2);
   canv_cross_et->SetTopMargin(0.04761905);
   canv_cross_et->SetBottomMargin(0.05);
   canv_cross_et->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: canv_cross_et_1
   TPad *canv_cross_et_1 = new TPad("canv_cross_et_1", "_1",0.1,0.4,0.9,0.9);
   canv_cross_et_1->Draw();
   canv_cross_et_1->cd();
   canv_cross_et_1->Range(2.256098,0.05,15.67073,2.6);
   canv_cross_et_1->SetFillColor(0);
   canv_cross_et_1->SetBorderMode(0);
   canv_cross_et_1->SetBorderSize(2);
   canv_cross_et_1->SetTickx(1);
   canv_cross_et_1->SetTicky(1);
   canv_cross_et_1->SetLeftMargin(0.13);
   canv_cross_et_1->SetRightMargin(0.05);
   canv_cross_et_1->SetTopMargin(0);
   canv_cross_et_1->SetBottomMargin(0);
   canv_cross_et_1->SetFrameBorderMode(0);
   canv_cross_et_1->SetFrameBorderMode(0);
   Double_t xAxis1[5] = {4, 6, 8, 10, 15}; 
   
   TH2D *h_window_cross_et = new TH2D("h_window_cross_et","",4, xAxis1,10,0.05,2.6);
   h_window_cross_et->SetStats(0);
   h_window_cross_et->GetXaxis()->SetTitle("E_{T}^{photon} (GeV)");
   h_window_cross_et->GetXaxis()->CenterTitle(true);
   h_window_cross_et->GetXaxis()->SetNdivisions(507);
   h_window_cross_et->GetXaxis()->SetLabelFont(42);
   h_window_cross_et->GetXaxis()->SetLabelSize(0.05073171);
   h_window_cross_et->GetXaxis()->SetTitleSize(0.06341463);
   h_window_cross_et->GetXaxis()->SetTitleFont(42);
   h_window_cross_et->GetYaxis()->SetTitle("d#sigma/d E_{T}^{photon} (pb/GeV)");
   h_window_cross_et->GetYaxis()->CenterTitle(true);
   h_window_cross_et->GetYaxis()->SetNdivisions(507);
   h_window_cross_et->GetYaxis()->SetLabelFont(42);
   h_window_cross_et->GetYaxis()->SetLabelSize(0.0416);
   h_window_cross_et->GetYaxis()->SetTitleSize(0.052);
   h_window_cross_et->GetYaxis()->SetTitleFont(42);
   h_window_cross_et->Draw("");
   Double_t xAxis2[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et = new TH1D("h_cross_section_et","det_cross_et",4, xAxis2);
   h_cross_section_et->SetBinContent(1,4.450064);
   h_cross_section_et->SetBinContent(2,2.113483);
   h_cross_section_et->SetBinContent(3,0.9970458);
   h_cross_section_et->SetBinContent(4,0.4281783);
   h_cross_section_et->SetBinError(1,0.3443503);
   h_cross_section_et->SetBinError(2,0.1795041);
   h_cross_section_et->SetBinError(3,0.1155849);
   h_cross_section_et->SetBinError(4,0.04047526);
   h_cross_section_et->SetEntries(22622);
   h_cross_section_et->SetFillColor(41);
   h_cross_section_et->SetMarkerStyle(20);
   h_cross_section_et->SetMarkerSize(0.8);
   h_cross_section_et->Draw("E3 SAME");
   Double_t xAxis3[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et_stat_fit_err = new TH1D("h_cross_section_et_stat_fit_err","det_cross_et",4, xAxis3);
   h_cross_section_et_stat_fit_err->SetBinContent(1,4.450064);
   h_cross_section_et_stat_fit_err->SetBinContent(2,2.113483);
   h_cross_section_et_stat_fit_err->SetBinContent(3,0.9970458);
   h_cross_section_et_stat_fit_err->SetBinContent(4,0.4281783);
   h_cross_section_et_stat_fit_err->SetBinError(1,0.318737);
   h_cross_section_et_stat_fit_err->SetBinError(2,0.166383);
   h_cross_section_et_stat_fit_err->SetBinError(3,0.1094377);
   h_cross_section_et_stat_fit_err->SetBinError(4,0.03660693);
   h_cross_section_et_stat_fit_err->SetEntries(22622);
   h_cross_section_et_stat_fit_err->SetFillColor(43);
   h_cross_section_et_stat_fit_err->Draw("E3 SAME");
   Double_t xAxis4[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et_acc_err = new TH1D("h_cross_section_et_acc_err","det_cross_et",4, xAxis4);
   h_cross_section_et_acc_err->SetBinContent(1,4.450064);
   h_cross_section_et_acc_err->SetBinContent(2,2.113483);
   h_cross_section_et_acc_err->SetBinContent(3,0.9970458);
   h_cross_section_et_acc_err->SetBinContent(4,0.4281783);
   h_cross_section_et_acc_err->SetBinError(1,0.05997486);
   h_cross_section_et_acc_err->SetBinError(2,0.03897246);
   h_cross_section_et_acc_err->SetBinError(3,0.02666923);
   h_cross_section_et_acc_err->SetBinError(4,0.01320014);
   h_cross_section_et_acc_err->SetEntries(22622);
   h_cross_section_et_acc_err->SetFillColor(46);
   h_cross_section_et_acc_err->Draw("E3 SAME");
   Double_t xAxis5[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et_lumi_err = new TH1D("h_cross_section_et_lumi_err","det_cross_et",4, xAxis5);
   h_cross_section_et_lumi_err->SetBinContent(1,4.450064);
   h_cross_section_et_lumi_err->SetBinContent(2,2.113483);
   h_cross_section_et_lumi_err->SetBinContent(3,0.9970458);
   h_cross_section_et_lumi_err->SetBinContent(4,0.4281783);
   h_cross_section_et_lumi_err->SetBinError(1,0.1157017);
   h_cross_section_et_lumi_err->SetBinError(2,0.05495057);
   h_cross_section_et_lumi_err->SetBinError(3,0.02592319);
   h_cross_section_et_lumi_err->SetBinError(4,0.01113264);
   h_cross_section_et_lumi_err->SetEntries(22622);
   h_cross_section_et_lumi_err->SetFillColor(49);
   h_cross_section_et_lumi_err->Draw("E3 SAME");
   Double_t xAxis6[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et = new TH1D("h_cross_section_et","det_cross_et",4, xAxis6);
   h_cross_section_et->SetBinContent(1,4.450064);
   h_cross_section_et->SetBinContent(2,2.113483);
   h_cross_section_et->SetBinContent(3,0.9970458);
   h_cross_section_et->SetBinContent(4,0.4281783);
   h_cross_section_et->SetBinError(1,0.3443503);
   h_cross_section_et->SetBinError(2,0.1795041);
   h_cross_section_et->SetBinError(3,0.1155849);
   h_cross_section_et->SetBinError(4,0.04047526);
   h_cross_section_et->SetEntries(22622);
   h_cross_section_et->SetFillColor(41);
   h_cross_section_et->SetMarkerStyle(20);
   h_cross_section_et->SetMarkerSize(0.8);
   h_cross_section_et->Draw("E1 X0 SAME");
   
   TLegend *leg = new TLegend(0.5,0.5,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_cross_section_et","ZEUS (332 pb^{-1})","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry=leg->AddEntry("h_cross_section_et_stat_fit_err","statistic & fit parameter unc.","f");
   entry->SetFillColor(43);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_et_acc_err","acceptance unc.","f");
   entry->SetFillColor(46);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_et_lumi_err","luminosity unc.","f");
   entry->SetFillColor(49);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_et","total unc.","fpl");
   entry->SetFillColor(41);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   leg->Draw();
   canv_cross_et_1->Modified();
   canv_cross_et->cd();
  
// ------------>Primitives in pad: canv_cross_et_2
   canv_cross_et_2 = new TPad("canv_cross_et_2", "_2",0.1,0.2,0.9,0.4);
   canv_cross_et_2->Draw();
   canv_cross_et_2->cd();
   canv_cross_et_2->Range(2.256098,-0.5416667,15.67073,0.325);
   canv_cross_et_2->SetFillColor(0);
   canv_cross_et_2->SetBorderMode(0);
   canv_cross_et_2->SetBorderSize(2);
   canv_cross_et_2->SetTickx(1);
   canv_cross_et_2->SetTicky(1);
   canv_cross_et_2->SetLeftMargin(0.13);
   canv_cross_et_2->SetRightMargin(0.05);
   canv_cross_et_2->SetTopMargin(0);
   canv_cross_et_2->SetBottomMargin(0.25);
   canv_cross_et_2->SetFrameBorderMode(0);
   canv_cross_et_2->SetFrameBorderMode(0);
   Double_t xAxis7[5] = {4, 6, 8, 10, 15}; 
   
   TH2D *h_window_cross_ratio_et = new TH2D("h_window_cross_ratio_et","",4, xAxis7,10,-0.325,0.325);
   h_window_cross_ratio_et->SetStats(0);
   h_window_cross_ratio_et->GetXaxis()->SetTitle("E_{T}^{photon} (GeV)");
   h_window_cross_ratio_et->GetXaxis()->CenterTitle(true);
   h_window_cross_ratio_et->GetXaxis()->SetNdivisions(507);
   h_window_cross_ratio_et->GetXaxis()->SetLabelFont(42);
   h_window_cross_ratio_et->GetXaxis()->SetLabelSize(0.09756097);
   h_window_cross_ratio_et->GetXaxis()->SetTitleSize(0.1219512);
   h_window_cross_ratio_et->GetXaxis()->SetTickLength(0.07);
   h_window_cross_ratio_et->GetXaxis()->SetTitleOffset(0.8);
   h_window_cross_ratio_et->GetXaxis()->SetTitleFont(42);
   h_window_cross_ratio_et->GetYaxis()->SetTitle("rel. uncertainty");
   h_window_cross_ratio_et->GetYaxis()->CenterTitle(true);
   h_window_cross_ratio_et->GetYaxis()->SetNdivisions(406);
   h_window_cross_ratio_et->GetYaxis()->SetLabelFont(42);
   h_window_cross_ratio_et->GetYaxis()->SetLabelSize(0.08533333);
   h_window_cross_ratio_et->GetYaxis()->SetTitleSize(0.1066667);
   h_window_cross_ratio_et->GetYaxis()->SetTitleOffset(0.5);
   h_window_cross_ratio_et->GetYaxis()->SetTitleFont(42);
   h_window_cross_ratio_et->Draw("");
   Double_t xAxis8[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et_ratio = new TH1D("h_cross_section_et_ratio","det_cross_et",4, xAxis8);
   h_cross_section_et_ratio->SetBinError(1,0.07738098);
   h_cross_section_et_ratio->SetBinError(2,0.08493279);
   h_cross_section_et_ratio->SetBinError(3,0.1159274);
   h_cross_section_et_ratio->SetBinError(4,0.09452898);
   h_cross_section_et_ratio->SetEntries(22622);
   h_cross_section_et_ratio->SetFillColor(41);
   h_cross_section_et_ratio->SetMarkerStyle(20);
   h_cross_section_et_ratio->SetMarkerSize(0.8);
   h_cross_section_et_ratio->Draw("E3 SAME");
   Double_t xAxis9[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et_stat_fit_err_ratio = new TH1D("h_cross_section_et_stat_fit_err_ratio","det_cross_et",4, xAxis9);
   h_cross_section_et_stat_fit_err_ratio->SetBinError(1,0.07162526);
   h_cross_section_et_stat_fit_err_ratio->SetBinError(2,0.07872451);
   h_cross_section_et_stat_fit_err_ratio->SetBinError(3,0.109762);
   h_cross_section_et_stat_fit_err_ratio->SetBinError(4,0.08549459);
   h_cross_section_et_stat_fit_err_ratio->SetEntries(22622);
   h_cross_section_et_stat_fit_err_ratio->SetFillColor(43);
   h_cross_section_et_stat_fit_err_ratio->Draw("E3 SAME");
   Double_t xAxis10[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et_acc_err_ratio = new TH1D("h_cross_section_et_acc_err_ratio","det_cross_et",4, xAxis10);
   h_cross_section_et_acc_err_ratio->SetBinError(1,0.0134773);
   h_cross_section_et_acc_err_ratio->SetBinError(2,0.01843992);
   h_cross_section_et_acc_err_ratio->SetBinError(3,0.02674825);
   h_cross_section_et_acc_err_ratio->SetBinError(4,0.03082861);
   h_cross_section_et_acc_err_ratio->SetEntries(22622);
   h_cross_section_et_acc_err_ratio->SetFillColor(46);
   h_cross_section_et_acc_err_ratio->Draw("E3 SAME");
   Double_t xAxis11[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et_lumi_err_ratio = new TH1D("h_cross_section_et_lumi_err_ratio","det_cross_et",4, xAxis11);
   h_cross_section_et_lumi_err_ratio->SetBinError(1,0.026);
   h_cross_section_et_lumi_err_ratio->SetBinError(2,0.026);
   h_cross_section_et_lumi_err_ratio->SetBinError(3,0.026);
   h_cross_section_et_lumi_err_ratio->SetBinError(4,0.026);
   h_cross_section_et_lumi_err_ratio->SetEntries(22622);
   h_cross_section_et_lumi_err_ratio->SetFillColor(49);
   h_cross_section_et_lumi_err_ratio->Draw("E3 SAME");
   Double_t xAxis12[5] = {4, 6, 8, 10, 15}; 
   
   TH1D *h_cross_section_et_ratio = new TH1D("h_cross_section_et_ratio","det_cross_et",4, xAxis12);
   h_cross_section_et_ratio->SetBinError(1,0.07738098);
   h_cross_section_et_ratio->SetBinError(2,0.08493279);
   h_cross_section_et_ratio->SetBinError(3,0.1159274);
   h_cross_section_et_ratio->SetBinError(4,0.09452898);
   h_cross_section_et_ratio->SetEntries(22622);
   h_cross_section_et_ratio->SetFillColor(41);
   h_cross_section_et_ratio->SetMarkerStyle(20);
   h_cross_section_et_ratio->SetMarkerSize(0.8);
   h_cross_section_et_ratio->Draw("E1 X0 SAME");
   canv_cross_et_2->Modified();
   canv_cross_et->cd();
   canv_cross_et->Modified();
   canv_cross_et->cd();
   canv_cross_et->SetSelected(canv_cross_et);
}
