{
//=========Macro generated from canvas: canv_cross_eta/
//=========  (Fri Mar 11 01:30:26 2011) by ROOT version5.26/00c
   TCanvas *canv_cross_eta = new TCanvas("canv_cross_eta", "",0,0,550,900);
   canv_cross_eta->SetHighLightColor(2);
   canv_cross_eta->Range(0,0,1,1);
   canv_cross_eta->SetFillColor(0);
   canv_cross_eta->SetBorderMode(0);
   canv_cross_eta->SetBorderSize(2);
   canv_cross_eta->SetTopMargin(0.04761905);
   canv_cross_eta->SetBottomMargin(0.05);
   canv_cross_eta->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: canv_cross_eta_1
   TPad *canv_cross_eta_1 = new TPad("canv_cross_eta_1", "_1",0.1,0.4,0.9,0.9);
   canv_cross_eta_1->Draw();
   canv_cross_eta_1->cd();
   canv_cross_eta_1->Range(-0.9536585,0.05,0.997561,8.5);
   canv_cross_eta_1->SetFillColor(0);
   canv_cross_eta_1->SetBorderMode(0);
   canv_cross_eta_1->SetBorderSize(2);
   canv_cross_eta_1->SetTickx(1);
   canv_cross_eta_1->SetTicky(1);
   canv_cross_eta_1->SetLeftMargin(0.13);
   canv_cross_eta_1->SetRightMargin(0.05);
   canv_cross_eta_1->SetTopMargin(0);
   canv_cross_eta_1->SetBottomMargin(0);
   canv_cross_eta_1->SetFrameBorderMode(0);
   canv_cross_eta_1->SetFrameBorderMode(0);
   Double_t xAxis13[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH2D *h_window_cross_eta = new TH2D("h_window_cross_eta","",4, xAxis13,10,0.05,8.5);
   h_window_cross_eta->SetStats(0);
   h_window_cross_eta->GetXaxis()->SetTitle("#eta_{photon}");
   h_window_cross_eta->GetXaxis()->CenterTitle(true);
   h_window_cross_eta->GetXaxis()->SetNdivisions(507);
   h_window_cross_eta->GetXaxis()->SetLabelFont(42);
   h_window_cross_eta->GetXaxis()->SetLabelSize(0.05073171);
   h_window_cross_eta->GetXaxis()->SetTitleSize(0.06341463);
   h_window_cross_eta->GetXaxis()->SetTitleFont(42);
   h_window_cross_eta->GetYaxis()->SetTitle("d#sigma/d #eta_{photon} (pb)");
   h_window_cross_eta->GetYaxis()->CenterTitle(true);
   h_window_cross_eta->GetYaxis()->SetNdivisions(507);
   h_window_cross_eta->GetYaxis()->SetLabelFont(42);
   h_window_cross_eta->GetYaxis()->SetLabelSize(0.0416);
   h_window_cross_eta->GetYaxis()->SetTitleSize(0.052);
   h_window_cross_eta->GetYaxis()->SetTitleFont(42);
   h_window_cross_eta->Draw("");
   Double_t xAxis14[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta = new TH1D("h_cross_section_eta","det_cross_eta",4, xAxis14);
   h_cross_section_eta->SetBinContent(1,12.97556);
   h_cross_section_eta->SetBinContent(2,11.68049);
   h_cross_section_eta->SetBinContent(3,10.39248);
   h_cross_section_eta->SetBinContent(4,6.480043);
   h_cross_section_eta->SetBinError(1,1.069656);
   h_cross_section_eta->SetBinError(2,1.004123);
   h_cross_section_eta->SetBinError(3,0.9665408);
   h_cross_section_eta->SetBinError(4,0.917661);
   h_cross_section_eta->SetEntries(22622);
   h_cross_section_eta->SetFillColor(41);
   h_cross_section_eta->SetMarkerStyle(20);
   h_cross_section_eta->SetMarkerSize(0.8);
   h_cross_section_eta->Draw("E3 SAME");
   Double_t xAxis15[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta_stat_fit_err = new TH1D("h_cross_section_eta_stat_fit_err","det_cross_eta",4, xAxis15);
   h_cross_section_eta_stat_fit_err->SetBinContent(1,12.97556);
   h_cross_section_eta_stat_fit_err->SetBinContent(2,11.68049);
   h_cross_section_eta_stat_fit_err->SetBinContent(3,10.39248);
   h_cross_section_eta_stat_fit_err->SetBinContent(4,6.480043);
   h_cross_section_eta_stat_fit_err->SetBinError(1,0.9796133);
   h_cross_section_eta_stat_fit_err->SetBinError(2,0.9311648);
   h_cross_section_eta_stat_fit_err->SetBinError(3,0.9074843);
   h_cross_section_eta_stat_fit_err->SetBinError(4,0.8936788);
   h_cross_section_eta_stat_fit_err->SetEntries(22622);
   h_cross_section_eta_stat_fit_err->SetFillColor(43);
   h_cross_section_eta_stat_fit_err->Draw("E3 SAME");
   Double_t xAxis16[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta_acc_err = new TH1D("h_cross_section_eta_acc_err","det_cross_eta",4, xAxis16);
   h_cross_section_eta_acc_err->SetBinContent(1,12.97556);
   h_cross_section_eta_acc_err->SetBinContent(2,11.68049);
   h_cross_section_eta_acc_err->SetBinContent(3,10.39248);
   h_cross_section_eta_acc_err->SetBinContent(4,6.480043);
   h_cross_section_eta_acc_err->SetBinError(1,0.2659067);
   h_cross_section_eta_acc_err->SetBinError(2,0.2212826);
   h_cross_section_eta_acc_err->SetBinError(3,0.1940693);
   h_cross_section_eta_acc_err->SetBinError(4,0.1226947);
   h_cross_section_eta_acc_err->SetEntries(22622);
   h_cross_section_eta_acc_err->SetFillColor(46);
   h_cross_section_eta_acc_err->Draw("E3 SAME");
   Double_t xAxis17[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta_lumi_err = new TH1D("h_cross_section_eta_lumi_err","det_cross_eta",4, xAxis17);
   h_cross_section_eta_lumi_err->SetBinContent(1,12.97556);
   h_cross_section_eta_lumi_err->SetBinContent(2,11.68049);
   h_cross_section_eta_lumi_err->SetBinContent(3,10.39248);
   h_cross_section_eta_lumi_err->SetBinContent(4,6.480043);
   h_cross_section_eta_lumi_err->SetBinError(1,0.3373645);
   h_cross_section_eta_lumi_err->SetBinError(2,0.3036928);
   h_cross_section_eta_lumi_err->SetBinError(3,0.2702045);
   h_cross_section_eta_lumi_err->SetBinError(4,0.1684811);
   h_cross_section_eta_lumi_err->SetEntries(22622);
   h_cross_section_eta_lumi_err->SetFillColor(49);
   h_cross_section_eta_lumi_err->Draw("E3 SAME");
   Double_t xAxis18[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta = new TH1D("h_cross_section_eta","det_cross_eta",4, xAxis18);
   h_cross_section_eta->SetBinContent(1,12.97556);
   h_cross_section_eta->SetBinContent(2,11.68049);
   h_cross_section_eta->SetBinContent(3,10.39248);
   h_cross_section_eta->SetBinContent(4,6.480043);
   h_cross_section_eta->SetBinError(1,1.069656);
   h_cross_section_eta->SetBinError(2,1.004123);
   h_cross_section_eta->SetBinError(3,0.9665408);
   h_cross_section_eta->SetBinError(4,0.917661);
   h_cross_section_eta->SetEntries(22622);
   h_cross_section_eta->SetFillColor(41);
   h_cross_section_eta->SetMarkerStyle(20);
   h_cross_section_eta->SetMarkerSize(0.8);
   h_cross_section_eta->Draw("E1 X0 SAME");
   
   TLegend *leg = new TLegend(0.37,0.059,0.77,0.458,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_cross_section_eta","ZEUS (332 pb^{-1})","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   entry=leg->AddEntry("h_cross_section_eta_stat_fit_err","statistic & fit parameter unc.","f");
   entry->SetFillColor(43);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_eta_acc_err","acceptance unc.","f");
   entry->SetFillColor(46);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_eta_lumi_err","luminosity unc.","f");
   entry->SetFillColor(49);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("h_cross_section_eta","total unc.","fpl");
   entry->SetFillColor(41);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.8);
   leg->Draw();
   canv_cross_eta_1->Modified();
   canv_cross_eta->cd();
  
// ------------>Primitives in pad: canv_cross_eta_2
   canv_cross_eta_2 = new TPad("canv_cross_eta_2", "_2",0.1,0.2,0.9,0.4);
   canv_cross_eta_2->Draw();
   canv_cross_eta_2->cd();
   canv_cross_eta_2->Range(-0.9536585,-0.5416667,0.997561,0.325);
   canv_cross_eta_2->SetFillColor(0);
   canv_cross_eta_2->SetBorderMode(0);
   canv_cross_eta_2->SetBorderSize(2);
   canv_cross_eta_2->SetTickx(1);
   canv_cross_eta_2->SetTicky(1);
   canv_cross_eta_2->SetLeftMargin(0.13);
   canv_cross_eta_2->SetRightMargin(0.05);
   canv_cross_eta_2->SetTopMargin(0);
   canv_cross_eta_2->SetBottomMargin(0.25);
   canv_cross_eta_2->SetFrameBorderMode(0);
   canv_cross_eta_2->SetFrameBorderMode(0);
   Double_t xAxis19[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH2D *h_window_cross_ratio_eta = new TH2D("h_window_cross_ratio_eta","",4, xAxis19,10,-0.325,0.325);
   h_window_cross_ratio_eta->SetStats(0);
   h_window_cross_ratio_eta->GetXaxis()->SetTitle("#eta_{photon}");
   h_window_cross_ratio_eta->GetXaxis()->CenterTitle(true);
   h_window_cross_ratio_eta->GetXaxis()->SetNdivisions(507);
   h_window_cross_ratio_eta->GetXaxis()->SetLabelFont(42);
   h_window_cross_ratio_eta->GetXaxis()->SetLabelSize(0.09756097);
   h_window_cross_ratio_eta->GetXaxis()->SetTitleSize(0.1219512);
   h_window_cross_ratio_eta->GetXaxis()->SetTickLength(0.07);
   h_window_cross_ratio_eta->GetXaxis()->SetTitleOffset(0.8);
   h_window_cross_ratio_eta->GetXaxis()->SetTitleFont(42);
   h_window_cross_ratio_eta->GetYaxis()->SetTitle("rel. uncertainty");
   h_window_cross_ratio_eta->GetYaxis()->CenterTitle(true);
   h_window_cross_ratio_eta->GetYaxis()->SetNdivisions(406);
   h_window_cross_ratio_eta->GetYaxis()->SetLabelFont(42);
   h_window_cross_ratio_eta->GetYaxis()->SetLabelSize(0.08533333);
   h_window_cross_ratio_eta->GetYaxis()->SetTitleSize(0.1066667);
   h_window_cross_ratio_eta->GetYaxis()->SetTitleOffset(0.5);
   h_window_cross_ratio_eta->GetYaxis()->SetTitleFont(42);
   h_window_cross_ratio_eta->Draw("");
   Double_t xAxis20[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta_ratio = new TH1D("h_cross_section_eta_ratio","det_cross_eta",4, xAxis20);
   h_cross_section_eta_ratio->SetBinError(1,0.08243621);
   h_cross_section_eta_ratio->SetBinError(2,0.08596581);
   h_cross_section_eta_ratio->SetBinError(3,0.09300386);
   h_cross_section_eta_ratio->SetBinError(4,0.1416134);
   h_cross_section_eta_ratio->SetEntries(22622);
   h_cross_section_eta_ratio->SetFillColor(41);
   h_cross_section_eta_ratio->SetMarkerStyle(20);
   h_cross_section_eta_ratio->SetMarkerSize(0.8);
   h_cross_section_eta_ratio->Draw("E3 SAME");
   Double_t xAxis21[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta_stat_fit_err_ratio = new TH1D("h_cross_section_eta_stat_fit_err_ratio","det_cross_eta",4, xAxis21);
   h_cross_section_eta_stat_fit_err_ratio->SetBinError(1,0.07549682);
   h_cross_section_eta_stat_fit_err_ratio->SetBinError(2,0.07971964);
   h_cross_section_eta_stat_fit_err_ratio->SetBinError(3,0.08732124);
   h_cross_section_eta_stat_fit_err_ratio->SetBinError(4,0.1379125);
   h_cross_section_eta_stat_fit_err_ratio->SetEntries(22622);
   h_cross_section_eta_stat_fit_err_ratio->SetFillColor(43);
   h_cross_section_eta_stat_fit_err_ratio->Draw("E3 SAME");
   Double_t xAxis22[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta_acc_err_ratio = new TH1D("h_cross_section_eta_acc_err_ratio","det_cross_eta",4, xAxis22);
   h_cross_section_eta_acc_err_ratio->SetBinError(1,0.0204929);
   h_cross_section_eta_acc_err_ratio->SetBinError(2,0.01894462);
   h_cross_section_eta_acc_err_ratio->SetBinError(3,0.01867401);
   h_cross_section_eta_acc_err_ratio->SetBinError(4,0.01893424);
   h_cross_section_eta_acc_err_ratio->SetEntries(22622);
   h_cross_section_eta_acc_err_ratio->SetFillColor(46);
   h_cross_section_eta_acc_err_ratio->Draw("E3 SAME");
   Double_t xAxis23[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta_lumi_err_ratio = new TH1D("h_cross_section_eta_lumi_err_ratio","det_cross_eta",4, xAxis23);
   h_cross_section_eta_lumi_err_ratio->SetBinError(1,0.026);
   h_cross_section_eta_lumi_err_ratio->SetBinError(2,0.026);
   h_cross_section_eta_lumi_err_ratio->SetBinError(3,0.026);
   h_cross_section_eta_lumi_err_ratio->SetBinError(4,0.026);
   h_cross_section_eta_lumi_err_ratio->SetEntries(22622);
   h_cross_section_eta_lumi_err_ratio->SetFillColor(49);
   h_cross_section_eta_lumi_err_ratio->Draw("E3 SAME");
   Double_t xAxis24[5] = {-0.7, -0.3, 0.1, 0.5, 0.9}; 
   
   TH1D *h_cross_section_eta_ratio = new TH1D("h_cross_section_eta_ratio","det_cross_eta",4, xAxis24);
   h_cross_section_eta_ratio->SetBinError(1,0.08243621);
   h_cross_section_eta_ratio->SetBinError(2,0.08596581);
   h_cross_section_eta_ratio->SetBinError(3,0.09300386);
   h_cross_section_eta_ratio->SetBinError(4,0.1416134);
   h_cross_section_eta_ratio->SetEntries(22622);
   h_cross_section_eta_ratio->SetFillColor(41);
   h_cross_section_eta_ratio->SetMarkerStyle(20);
   h_cross_section_eta_ratio->SetMarkerSize(0.8);
   h_cross_section_eta_ratio->Draw("E1 X0 SAME");
   canv_cross_eta_2->Modified();
   canv_cross_eta->cd();
   canv_cross_eta->Modified();
   canv_cross_eta->cd();
   canv_cross_eta->SetSelected(canv_cross_eta);
}
